description: pretrain_bert

target:
  service: amlk8s
  # run "amlt target list amlk8s" to list the names of available AMLK8s targets
  name: itpscusv100cl 
  #name: itpeusp40cl 
  #name: itplabrl1cl1
  #name: itpeusp100cl
  #name: itplabrr1cl1
  #name: itpscusv100cl 
  #name: itpwus2v100cl
  #name: itpseasiav100cl 
  #name: itpeastusv100cl
  vc: resrchvc

environment:
  image: pytorch/pytorch:1.5.1-cuda10.1-cudnn7-devel
  registry: registry.hub.docker.com # any public registry can be specified here
  username: vespertinux


code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: C:\Users\v-zelinli\Temp\MSRA\pretrain_bert_with_maskLM\


storage:
    output:
        storage_account_name: usscv100data
        container_name: v-zelinli
        mount_dir: /mnt/output

jobs:
  - name: run_vanilla
    sku: G1-V100
    command:
      - python train.py

